dotnet isolated fsharp templates
Azure/azure-functions-templates pull request #1074
Opened 2021-07-28 05:47 UTC by aaronpowell

This adds project and item templates for F# under the dotnet-isolated project model.

The item templates match what originally existed for F#, so there are a few gaps still compared to the C# templates, but this brings the dotnet-isolated experience up to where we were with the in process model for F# dev.

2021-08-10 15:10 UTC, dsyme commented
This is fantastic, it will be so good to have the templates supported

2021-09-14 12:23 UTC, mabasic commented
Will this be in the v4 and in v3, or just v4?

2021-09-14 13:53 UTC, joshuapassos commented
Anything holding this back from being merged?

2021-09-14 23:57 UTC, aaronpowell commented
> Will this be in the v4 and in v3, or just v4?

It's possible that this could be back ported to the v3 branch, but I created it against v4 as that's the currently active dev branch.

> Anything holding this back from being merged?

Just waiting for review from someone on the Functions team. @soninaren @fabiocav would either of you have time to review this?

2021-10-06 20:30 UTC, soninaren requested changes

2021-10-06 20:30 UTC, soninaren commented on Functions.Templates/ProjectTemplate/FSharp-Isolated/Company.FunctionApp.fsproj
> +    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer"/>
might be good to update to `1.1.0-preview.1`

2021-10-06 20:30 UTC, soninaren commented on Functions.Templates/Templates/BlobTrigger-FSharp-Isolated/.template.config/template.json
> +    "identity": "Azure.Function.FSharp.BlobTrigger.2.x",
need to add `isolated` to identity

2021-11-02 00:14 UTC, aaronpowell commented
@soninaren anything more outstanding on these that you'd like me to address?

2021-11-08 23:28 UTC, soninaren commented
@aaronpowell, Looks like your original changes were correct. I will merge and sync your template changes with c#.

2021-12-10 01:13 UTC, fabiocav commented
@soninaren your last comment here was a while ago. Is there a reason why this hasn't been merged yet? Can we please have this in ASAP?

2021-12-14 18:11 UTC, merged